# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#

ben = Areana.create(name: "Ben Hill Griffin Stadium", capacity: 88000, state: "Florida", city: "Gainesville", conference: "SEC")
bryant = Areana.create(name: "Bryant-Denny Stadium", capacity: 101000, state: "Alabama", city: "Tuscaloosa", conference: "SEC")
kyle = Areana.create(name: "Kyle Field", capacity: 102000, state: "Texas", city: "College Station", conference: "SEC")
sanford = Areana.create(name: "Sanford Stadium", capacity: 92000, state: "Georgia", city: "Athens", conference: "SEC")
neyland = Areana.create(name: "Neyland Stadium", capacity: 102000, state: "Tennessee", city: "Knoxville", conference: "SEC")
jordan = Areana.create(name: "Jordan-Hare", capacity: 87000, state: "Alabama", city: "Auburn", conference: "SEC")
brice = Areana.create(name: "Williams-Brice Stadium", capacity: 80000, state: "South Carolina", city: "Columbia", conference: "SEC")
lsu_tiger = Areana.create(name: "LSU Tiger Stadium", capacity: 102000, state: "Louisiana", city: "Baton Rouge", conference: "SEC")
razorback = Areana.create(name: "Razorback Stadium", capacity: 72000, state: "Arkansas", city: "Fayetteville", conference: "SEC")
faurot = Areana.create(name: "Faurot Field", capacity: 71000, state: "Missouri", city: "Columbia", conference: "SEC")
vaught = Areana.create(name: "Vaught Hemingway Stadium", capacity: 64000, state: "Mississippi", city: "Oxford", conference: "SEC")
wade = Areana.create(name: "Davis Wade Stadium", capacity: 61000, state: "Mississippi", city: "Starkville", conference: "SEC")
kroger = Areana.create(name: "Kroger Field", capacity: 61000, state: "Kentucky", city: "Lexington", conference: "SEC")
vanderbilt = Areana.create(name: "Vanderbilt Stadium", capacity: 40000, state: "Tennessee", city: "Nashville", conference: "SEC")
doak = Areana.create(name: "Doak Campbell Stadium", capacity: 79000, state: "Florida", city: "Tallahassee", conference: "ACC")

clemson = Areana.create(name: "Clemson Memorial Stadium", capacity: 81000, state: "South Carolina", city: "Clemson", conference: "ACC")
pitt = Areana.create(name: "Heinz Field", capacity: 68400, state: "Pennsylvania", city: "Pittsburgh", conference: "ACC")
vtech = Areana.create(name: "Lane Stadium", capacity: 66000, state: "Virginia", city: "Blacksburg", conference: "ACC")
miami = Areana.create(name: "Hard Rock Stadium", capacity: 65000, state: "Florida", city: "Miami", conference: "ACC")
unc = Areana.create(name: "Kenan Memorial Stadium", capacity: 62000, state: "North Carolina", city: "Chapel Hill", conference: "ACC")
virginia = Areana.create(name: "Scott Stadium", capacity: 61500, state: "Virginia", city: "Charlottesville", conference: "ACC")
ncstate = Areana.create(name: "Carter Finley Stadium", capacity: 57500, state: "North Carolina", city: "Raleigh", conference: "ACC")
gtech = Areana.create(name: "Bobby Dodd Stadium", capacity: 55000, state: "Georgia", city: "Atlanta", conference: "ACC")
louisville = Areana.create(name: "Cardinal Stadium", capacity: 55000, state: "Kentucky", city: "Louisville", conference: "ACC")
cuse = Areana.create(name: "Carrier Dome", capacity: 49000, state: "New York", city: "Syracuse", conference: "ACC")
boston = Areana.create(name: "Alumni Stadium", capacity: 44500, state: "Massachusetts", city: "Boston", conference: "ACC")
duke = Areana.create(name: "Wallace Wade Stadium", capacity: 40000, state: "North Carolina", city: "Durham", conference: "ACC")
wake = Areana.create(name: "BB&T Field", capacity: 31500, state: "North Carolina", city: "Winston-Salem", conference: "ACC")

texas = Areana.create(name: "Darrel K. Royal-Texas Memorial Stadium", capacity: 102000, state: "Texas", city: "Austin", conference: "Big 12")
ou = Areana.create(name: "Gaylord Family-Oklahoma Memorial Stadium", capacity: 86000, state: "Oklahoma", city: "Norman", conference: "Big 12")
iowast = Areana.create(name: "Jack Trice Stadium", capacity: 61500, state: "Iowa", city: "Ames", conference: "Big 12")
texastech = Areana.create(name: "Jones AT&T Stadium", capacity: 61000, state: "Texas", city: "Lubbock", conference: "Big 12")
okst = Areana.create(name: "Boone Pickens Stadium", capacity: 60000, state: "Oklahoma", city: "Stillwater", conference: "Big 12")
wvu = Areana.create(name: "Mountaineer Field", capacity: 60000, state: "West Virginia", city: "Morgantown", conference: "Big 12")
kansas = Areana.create(name: "Memorial Stadium Kansas", capacity: 50000, state: "Kansas", city: "Lawrence", conference: "Big 12")
kstate = Areana.create(name: "Bill Snyder Family Stadium", capacity: 50000, state: "Kansas", city: "Manhattan", conference: "Big 12")
baylor = Areana.create(name: "McLane Stadium", capacity: 45000, state: "Texas", city: "Waco", conference: "Big 12")

















































kyle.images.create(photo: "https://12thman.com/images/2017/1/23/kyle4.jpg")
kyle.images.create(photo: "https://12thman.com/images/2016/3/23/Kyle_Field_aerial_2015_6x9.jpg")
kyle.images.create(photo: "http://www.walterpmoore.com/sites/default/files/styles/panopoly_image_original/public/kyle_field_20150910_dig_0072_mas_2.jpg?itok=VvnPm8f1")
tcu = Areana.create(name: "Amon G. Carter Stadium", capacity: 45000, state: "Texas", city: "Fort Worth", conference: "Big 12")
sanford.images.create(photo: "https://georgiadogs.com/images/2016/5/20/sanford16-06.jpg")
sanford.images.create(photo: "http://thegeorgiabulldogclub.com/uploads/main/Facilites-Sanford-590x330-14.jpg")
sanford.images.create(photo: "http://www.exploregeorgia.org/master/img/blog/2016/07/sanford-stadium-game-day-credit-broad-collective-2.jpg")
jordan.images.create(photo: "https://i0.wp.com/altoday.com/wp-content/uploads/2017/01/Jordan-Hare-Stadium.jpg?fit=1245%2C492")
jordan.images.create(photo: "https://s3media.247sports.com/Uploads/Assets/426/84/6_5084426.jpg")
jordan.images.create(photo: "https://www.auburn.edu/administration/facilities/images/buildings/AA_T0501_3.jpg")
ben.images.create(photo: "https://floridagators.com/images/2015/12/14//swamp-20121006-lsu_0378.jpg")
ben.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/0/07/Ben_Hill_Griffin_Stadium.jpg")
ben.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/BenHillGriffinStadium.png/1200px-BenHillGriffinStadium.png")
bryant.images.create(photo: "https://www.brasfieldgorrie.com/wp-content/uploads/Bryant-Denny-Stadium-1-main-578x325.jpg")
bryant.images.create(photo: "http://gridironnow.com/wp-content/uploads/2017/01/bryantdenny.jpg")
bryant.images.create(photo: "https://s3.amazonaws.com/rolltide.com/images/2016/6/21/6942191.jpeg")
neyland.images.create(photo: "http://theblacksheeponline.com/wp-content/uploads/2017/11/empty-neyland.jpg")
neyland.images.create(photo: "https://res.cloudinary.com/cmgverticals/image/upload/c_crop,g_north_west,h_534,w_1024,x_0,y_85/c_fill,h_628,q_80,w_1200/e_sharpen,f_auto,fl_lossy,q_auto/v1478902835/Neyland-Stadium-by-Joe-MurphyGetty-Images_oavkki.jpg")
neyland.images.create(photo: "https://www.rockytopinsider.com/wp-content/uploads/2015/08/Neyland-Stadium.jpg")
brice.images.create(photo: "https://imagesvc.timeincapp.com/v3/mm/image?url=https%3A%2F%2Fcdn-s3.si.com%2Fs3fs-public%2Fstyles%2Fmarquee_large_2x%2Fpublic%2Fimages%2Fwilliams-brice-stadium-spotlight-south-carolina-gamecocks.jpg%3Fitok%3DcLeJBNpl&w=1100&q=85")
brice.images.create(photo: "https://media.sportsmatik.com/wiki-gallery/venues/Williams-Brice_Stadium4_1493039952_75244.jpg")
brice.images.create(photo: "https://www.collegeexpertmn.com/wordpress/wp-content/uploads/2015/10/USC-Football-Stadium.jpg")
lsu_tiger.images.create(photo: "http://www.lsu.edu/mediacenter/mediaimages/2017/01/LSU2207-Tiger-Stadium.jpg")
lsu_tiger.images.create(photo: "https://www.fitsnews.com/wp-content/uploads/2012/10/lsu-death-valley.jpg")
lsu_tiger.images.create(photo: "https://media.klfy.com/nxs-klfytv-media-us-east-1/photo/2017/09/07/14856696_g_29735937_ver1.0_640_360.jpg")
razorback.images.create(photo: "http://www.arkansasrazorbacks.com/wp-content/uploads/2017/03/Razorback-Stadium-FB-2016-6814.gif")
razorback.images.create(photo: "https://cdn-s3.si.com/s3fs-public/2017/03/30/arkansas-stadium-gun-ban.jpg")
razorback.images.create(photo: "http://arkansasrazorbacks.com/dwrrs-original/images/new/jared-2a.jpg")
faurot.images.create(photo: "https://mutigers.com/images/2015/6/9/8104782.jpeg")
faurot.images.create(photo: "https://mutigers.com/images/2015/8/26/8267679.jpeg")
faurot.images.create(photo: "https://mizzoumag.missouri.edu/wp-content/uploads/2013/08/Stadium_web.jpg")
vaught.images.create(photo: "https://media-cdn.tripadvisor.com/media/photo-s/09/54/4c/6f/oxford.jpg")
vaught.images.create(photo: "https://vignette.wikia.nocookie.net/collegefootballmania/images/3/3e/Ole_stadia.jpeg/revision/latest?cb=20120118200435")
vaught.images.create(photo: "https://a.vsstatic.com/mobile/venue/vaught-hemingway-stadium.jpg")
wade.images.create(photo: "https://c1.staticflickr.com/3/2950/15296922588_d3dc7841cc_b.jpg")
wade.images.create(photo: "https://www.msstate.edu/sites/www.msstate.edu/files/9-10-2010.jpg")
wade.images.create(photo: "https://i.ytimg.com/vi/DMePH9n-OA8/maxresdefault.jpg")
kroger.images.create(photo: "https://kentuckianareporters.com/wp-content/uploads/CommonwealthStadium2.jpg")
kroger.images.create(photo: "http://rosstarrant.com/wp-content/uploads/2017/03/Commonwealth-36.jpg")
kroger.images.create(photo: "https://res.cloudinary.com/simpleview/image/fetch/c_limit,f_auto,q_75,w_1200/https://Lexington.simpleviewcrm.com/images/listings/original_Kroger-Field---UK-Football-Stadium.jpg")
vanderbilt.images.create(photo: "https://res.cloudinary.com/cmgverticals/image/upload/c_crop,g_north_west,h_1581,w_3000,x_0,y_418/c_fill,h_628,q_80,w_1200/e_sharpen,f_auto,fl_lossy,q_auto/v1509813283/Vanderbilt-stadium-Grant-Halverson-Getty-Images-Vanderbilt-2011-DRC_4884_eankjb.jpg")
vanderbilt.images.create(photo: "http://news.vanderbilt.edu/files/Football-feature.jpg")
vanderbilt.images.create(photo: "https://usatodaysports.files.wordpress.com/2016/09/636029011193065777-vanderbilt-stadium.jpg?w=1000&h=666")

doak.images.create(photo: "http://fightmusic.com/wallpapers/acc/ACC_Florida_State__Doak_Campbell_Stadium__1920x1200.jpg")
doak.images.create(photo: "http://images.performgroup.com/di/library/omnisport/c6/eb/doak-campbell-stadium-112515-getty-ftr-usjpg_t7qmur06ghp21qhketcycwd0y.jpg?t=1106324041")
doak.images.create(photo: "https://c1.staticflickr.com/9/8125/8613800876_a0fa0fc9d8_b.jpg")
clemson.images.create(photo: "http://image.cdnllnwnl.xosnetwork.com/fls/28500/old_site/images/stadium_500.jpg")
clemson.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/MemorialStadiumSept2006.jpg/1200px-MemorialStadiumSept2006.jpg")
clemson.images.create(photo: "https://graphicjuice318.files.wordpress.com/2012/09/howards-rock.jpg")
pitt.images.create(photo: "http://a.espncdn.com/photo/2008/0730/heinz_580.jpg")
pitt.images.create(photo: "https://fansided.com/wp-content/blogs.dir/229/files/2013/09/5622688.jpg")
pitt.images.create(photo: "http://pittsburghpanthers.com/images/2015/6/17/facilities-heinz-field-15.jpg")
vtech.images.create(photo: "http://www.ivanmorozov.com/img/s/v-3/p2362030035-3.jpg")
vtech.images.create(photo: "https://i.pinimg.com/originals/19/dc/ce/19dccefa3bcd35f1e48200ff29b9c91f.jpg")
vtech.images.create(photo: "https://c1.staticflickr.com/6/5329/10127223113_12078a39e4_b.jpg")
miami.images.create(photo: "https://hurricanesports.com/images/2017/12/19/111117_UMvsND_pm311.jpg")
miami.images.create(photo: "https://cdn-s3.si.com/images/2016-1008-Miami-fans-throwing-water-bottles-ZYP_1541.jpg")
miami.images.create(photo: "http://canespace.typepad.com/.a/6a00e008c67258883401bb0932fa6c970d-500wi")
unc.images.create(photo: "https://res.cloudinary.com/simpleview/image/upload/crm/chapelhill/KenanStadium.FBjmu5710_2b118b44-5056-b3a8-4939c84310d2e7b4.jpg")
unc.images.create(photo: "https://www.unc.edu/wp-content/uploads/2018/01/019517_fb_notre_dame_north_carolina109.jpg")
unc.images.create(photo: "https://goheels.com/images/2012/3/13/YWLAMWASJICPMDM.20120313041210.jpg?width=1440&height=810&mode=crop")
virginia.images.create(photo: "https://bloximages.newyork1.vip.townnews.com/dailyprogress.com/content/tncms/assets/v3/editorial/f/cc/fcce3eda-1d91-11e3-8f89-001a4bcf6878/5234ecc3e3eae.image.jpg")
virginia.images.create(photo: "https://i.pinimg.com/originals/f4/ca/49/f4ca496dc8fba20cf8a0cae91af023b8.jpg")
virginia.images.create(photo: "https://media.gettyimages.com/photos/the-virginia-cavaliers-play-host-to-the-syracuse-orangemen-during-picture-id51358376?k=6&m=51358376&s=612x612&w=0&h=gKTkoSnOS88ZnN2kGffF8I5WJd_CwiG5liRV4pa_-bE=")
ncstate.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2015/09/Overview-of-Interior.jpg")
ncstate.images.create(photo: "http://aviewfrommyseat.com/wallpaper/jb2e75-20151031205947.jpg")
ncstate.images.create(photo: "https://files.sharenator.com/nc1_Carter_Finley_Stadium-s650x433-59619.jpg")
gtech.images.create(photo: "http://grfx.cstv.com/photos/schools/geot/sports/m-footbl/auto_original/6452308.jpeg")
gtech.images.create(photo: "https://www.ajc.com/rf/image_large/Pub/p8/AJC/2017/01/05/Images/newsEngin.17222858_092316-ga-tech-photos-HS12.jpg")
gtech.images.create(photo: "http://images.performgroup.com/di/library/Goal_America/d/21/bobby-dodd-stadium_1vcdxhgigb15w1hzksyi6j5bu0.jpg?t=-1779922015&w=800&h=600")
louisville.images.create(photo: "http://www.stadiumbleachers.com/images/portfolio/DC10A0DF6B415EB17D4C55B6.jpg")
louisville.images.create(photo: "http://wac.b63f.edgecastcdn.net/80B63F/images/sidearm.sites/gocards.com/images/2016/8/29/PJCS_web.jpg")
louisville.images.create(photo: "https://media.gannett-cdn.com/courierjournal/brightcove/29913742001/201602/1406/29913742001_4739080323001_4738997554001-vs.jpg")
cuse.images.create(photo: "https://cuse.com/images/facilities/dome/dome_1.jpg")
cuse.images.create(photo: "https://i.pinimg.com/originals/7c/05/c3/7c05c365b89d35d5fba3c1a9afeb9042.jpg")
cuse.images.create(photo: "https://c1.staticflickr.com/7/6045/6416415261_9a9732914f_b.jpg")
boston.images.create(photo: "http://www.bc.edu/alumni/news/news_directory/2014/bcaa_usc_trip/_jcr_content/newscontent/bcimage.img.jpg/1378760735517.jpg")
boston.images.create(photo: "http://appliedlt.com/wp-content/uploads/2012/10/Boston-College-Newton-MA1.jpg")
boston.images.create(photo: "http://bceagles.com/images/2015/9/23/Alumni_Stadium_Aerial_2007_32.JPG")
duke.images.create(photo: "https://mcadamsco.com/wp-content/uploads/2017/02/wallacewade-1545x645.jpg")
duke.images.create(photo: "http://image.cdnllnwnl.xosnetwork.com/pics33/800/GF/GFFHUQFNWZPXVHD.20170920175448.jpg")
duke.images.create(photo: "https://today.duke.edu/sites/default/files/styles/story_hero/public/Wallace%20Wade%201%20HERO.jpg?itok=cY9lwcRH")
wake.images.create(photo: "http://grfx.cstv.com/photos/schools/wake/sports/m-footbl/auto_a_astorywide/12724736.jpeg")
wake.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/BBT_Field_Deacon_Tower_Wake_Forest_University_football_stadium.jpg")
wake.images.create(photo: "http://grfx.cstv.com/photos/schools/wake/sports/m-footbl/auto_a_astorywide/12029293.jpeg")

texas.images.create(photo: "https://texasboxoffice.com/files/venues/darrell-k-royal-texas-memorial-stadium.jpg")
texas.images.create(photo: "http://youngandpratt.com/wp/wp-content/uploads/UT-NEZ-3.jpg")
texas.images.create(photo: "http://aviewfrommyseat.com/photos/morjesta-20140909164033.jpg")
ou.images.create(photo: "https://i.ytimg.com/vi/kBswGNc17-Q/maxresdefault.jpg")
ou.images.create(photo: "https://static.giantbomb.com/uploads/original/0/46/1834945-ou.jpg")
ou.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2016/11/Gaylord-Family-Oklahoma-Memorial-Stadium-Interior-900x675.jpg")
iowast.images.create(photo: "http://cyclones.com/images/2016/2/17/JackTriceStadium5.jpg")
iowast.images.create(photo: "http://fredsportsextra.com/wp-content/uploads/2016/07/jack-trice-stadium.jpg")
iowast.images.create(photo: "https://bloximages.chicago2.vip.townnews.com/iowastatedaily.com/content/tncms/assets/v3/editorial/5/4c/54c30cd2-55a9-11e5-9bcb-abc534f2956b/55ee05429fc26.image.jpg")
texastech.images.create(photo: "https://texastech.com/images/2017/9/7/rrfb_v_ewu_170902_119.jpg")
texastech.images.create(photo: "https://a.vsstatic.com/mobile/app/ncaaf/texas-tech-red-raiders.jpg")
michigan = Areana.create(name: "Michigan Stadium", capacity: 107500, state: "Michigan", city: "Ann Arbor", conference: "Big 10")
texastech.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2017/08/Tech3-900x675.jpg")
okst.images.create(photo: "https://c1.staticflickr.com/7/6156/6211775397_e84f800d71_b.jpg")
okst.images.create(photo: "https://res.cloudinary.com/cmgverticals/image/upload/c_crop,g_north_west,h_1578,w_3000,x_0,y_96/c_fill,h_628,q_80,w_1200/e_sharpen,f_auto,fl_lossy,q_auto/v1502913923/GettyImages-497329734_xqvaud.jpg")
pennst = Areana.create(name: "Beaver Stadium", capacity: 106500, state: "Pennsylvania", city: "University Park", conference: "Big 10")
okst.images.create(photo: "https://cdn.unifiedcommerce.com/content/product/large/91448.jpg")
wvu.images.create(photo: "https://www.tourmorgantown.com/wp-content/uploads/2015/07/field.jpg")
wvu.images.create(photo: "http://cdn.onlyinyourstate.com/wp-content/uploads/2015/04/fb-stadium-700x372.jpg")
ohiost = Areana.create(name: "Ohio Stadium", capacity: 105000, state: "Ohio", city: "Columbus", conference: "Big 10")
wvu.images.create(photo: "http://www.bluegoldsports.com/wp-content/uploads/2015/08/tra_wvu14_800.jpg")
kansas.images.create(photo: "https://kuathletics.com/common/controls/image_handler.aspx?thumb_id=0&image_path=/images/2017/8/21/parallax_image_memorial_stadium.png")
kansas.images.create(photo: "https://images.gametime.co/memorial-stadium-kansas/gametime-images/v2/memorial_stadium_kansas/cfb_kan/23@4x/lower-sideline-23.jpg?auto=webp&format=pjpg&quality=80&disable=upscale&dpr=1&fit=crop&width=520&height=200")
nebraska = Areana.create(name: "Memorial Stadium Nebraska", capacity: 85500, state: "Nebraska", city: "Lincoln", conference: "Big 10")
kansas.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Aerial_View_of_University_of_Kansas_Stadium_08-31-2013.jpg/1200px-Aerial_View_of_University_of_Kansas_Stadium_08-31-2013.jpg")
kstate.images.create(photo: "https://files.kstatecollegian.com/2017/08/20161126_SunflowerShowdown.EN-21.jpg")
kstate.images.create(photo: "http://thepost.s3.amazonaws.com/wp-content/uploads/2014/08/9913002.jpeg")
wisconsin = Areana.create(name: "Camp Randall Stadium", capacity: 80000, state: "Wisconsin", city: "Madison", conference: "Big 10")
kstate.images.create(photo: "https://www.wibwnewsnow.com/wp-content/uploads/2016/12/Bill-Snyder-stadium.jpg")
baylor.images.create(photo: "http://grfx.cstv.com/schools/bay/graphics/mclane-stadium-facilities-15.png")
baylor.images.create(photo: "https://www.baylor.edu/content/imglib/2/8/9/7/289749.jpg")
spartan = Areana.create(name: "Spartan Stadium (Michigan)", capacity: 75000, state: "Michigan", city: "East Lansing", conference: "Big 10")
baylor.images.create(photo: "http://www.flintco.com/uploads/gallery_images/cache/1622_570x470_crop_p19h60966p1cgf1volna132219kq5.jpg?1528342518")
tcu.images.create(photo: "http://www.52dazhew.com/data/out/216/587362680-tcu-horned-frogs-desktop-wallpaper.jpg")
tcu.images.create(photo: "http://aviewfrommyseat.com/wallpaper/IsiMan84-20161014040345.jpg")
iowa = Areana.create(name: "Kinnick Stadium", capacity: 70500, state: "Iowa", city: "Iowa City", conference: "Big 10")
tcu.images.create(photo: "https://s-media-cache-ak0.pinimg.com/originals/71/a8/3c/71a83c429d9c4b4358e73f2f89d0357e.jpg")

michigan.images.create(photo: "http://mediad.publicbroadcasting.net/p/michigan/files/styles/medium/public/201109/800px-MichiganStadium2010.JPG")
illinois = Areana.create(name: "Memorial Stadium", capacity: 60500, state: "Illinois", city: "Champaign", conference: "Big 10")
michigan.images.create(photo: "http://image.mlive.com/home/mlive-media/width620/img/wolverines_impact/photo/michigan-stadium-for-colorado-game-2016-junfujpg-0767a6267f9c0c44.jpg")
michigan.images.create(photo: "http://cdn3.sportngin.com/attachments/photo/4008/3726/3860cbf2-6034-49ea-8f72-30e068a44ca3.JPG")
pennst.images.create(photo: "http://www.post-gazette.com/image/2017/10/22/1140x_q90_a10-7_cTC_ca0,0,2600,1613/20171021acPennStatevsMichigan15.jpg")
purdue = Areana.create(name: "Ross-Ade Stadium", capacity: 57000, state: "Indiana", city: "West Lafayette", conference: "Big 10")
pennst.images.create(photo: "http://image.pennlive.com/home/penn-media/width620/img/pennstatefootball_impact/photo/penn-state-vs-michigan-oct-21-2017-9ecd0e67ddd49bb9.jpg")
pennst.images.create(photo: "http://cityportals-statecollegecom-assets.s3.amazonaws.com/assets/news/images/1471421_32282.jpg")
ohiost.images.create(photo: "http://grfx.cstv.com/schools/osu/graphics/facilities/stadium-day-800x325.jpg")
indiana = Areana.create(name: "Memorial Stadium Indiana", capacity: 53000, state: "Indiana", city: "Bloomington", conference: "Big 10")
ohiost.images.create(photo: "https://theozone.net/wp-content/uploads/2017/05/StadiumAtNight_700.jpg")
ohiost.images.create(photo: "https://image.mlive.com/home/mlive-media/width620/img/sports_impact/photo/horseshoe-photo-aerial-plain-dealerjpg-0fe6a0868687ec9c.jpg")
nebraska.images.create(photo: "https://hello.travefy.com/wp-content/uploads/2014/05/Memorial-Stadium.jpg")
rutgers = Areana.create(name: "High Point Solutions Stadium", capacity: 52500, state: "New Jersey", city: "Piscataway", conference: "Big 10")
nebraska.images.create(photo: "https://bloximages.newyork1.vip.townnews.com/omaha.com/content/tncms/assets/v3/editorial/4/39/439fdec0-4875-11e6-b638-9be6c62f0a21/57855d4f4e3dc.image.jpg")
nebraska.images.create(photo: "http://www.huskers.com/pics7/800/CC/CCFGXTWRFFRJBPH.20060912201218.jpg")
wisconsin.images.create(photo: "https://supportthebadgers.athletics.wisc.edu/assets/images/JPEGs/campaigns/2015/completed/cr_reno_rec_v_3_0_0_1170w500h100r40q.jpg")
maryland = Areana.create(name: "Maryland Stadium", capacity: 52000, state: "Maryland", city: "College Park", conference: "Big 10")
wisconsin.images.create(photo: "http://stadiums.at.ua/_nw/90/03666296.jpg")
wisconsin.images.create(photo: "https://cdn.shopify.com/s/files/1/1144/2816/products/Camp_Randall_Stadium_1024x1024.JPG?v=1455132121")
spartan.images.create(photo: "https://images.fineartamerica.com/images-medium-large-5/spartan-stadium-rey-del-rio.jpg")
minn = Areana.create(name: "TCF Bank Stadium", capacity: 51000, state: "Minnesota", city: "Minneapolis", conference: "Big 10")
spartan.images.create(photo: "https://cbsdetroit.files.wordpress.com/2014/10/153100236.jpg?w=1024&h=576&crop=1")
spartan.images.create(photo: "https://image.mlive.com/home/mlive-media/width620/img/lansing-news/photo/spartan-stadium-courtesy-msu-6e4aa080fd1a097d.jpg")
iowa.images.create(photo: "https://s.abcnews.com/images/Entertainment/GTY_kinnick_stadium2_cf_160623_12x5_992.jpg")
northwestern = Areana.create(name: "Ryan Field", capacity: 47000, state: "Illinois", city: "Evanston", conference: "Big 10")
iowa.images.create(photo: "https://i.ytimg.com/vi/grOISS9NevI/maxresdefault.jpg")
iowa.images.create(photo: "http://www.newtondailynews.com/_internal/cimg!0/rpk8i7vtorx8uau3jx6xoirxy7sez15")
illinois.images.create(photo: "http://theblacksheeponline.com/wp-content/uploads/2016/10/memorialstadium-videoboard-concept.jpg")
illinois.images.create(photo: "http://s3.amazonaws.com/sidearm.sites/fightingillini.com/images/2015/6/29/memorialstadium_2014.jpg")
usc = Areana.create(name: "Los Angeles Memorial Coliseum", capacity: 93500, state: "California", city: "Los Angeles", conference: "Pac 12")
illinois.images.create(photo: "http://fightmusic.com/wallpapers/big10/Big-Ten_Illinois__Memorial_Stadium__1600x1200.jpg")
purdue.images.create(photo: "http://graphics.fansonly.com/schools/pur/graphics/ross-ade-stadium-01-091117.jpg")
purdue.images.create(photo: "https://media-cdn.tripadvisor.com/media/photo-s/0d/6d/f5/be/the-purdue-marching-band.jpg")
ucla = Areana.create(name: "Rose Bowl", capacity: 91000, state: "California", city: "Pasadena", conference: "Pac 12")
purdue.images.create(photo: "https://www.purdue.edu/purdue/about/picture-your-purdue/images/2017-11/1104.jpg")
indiana.images.create(photo: "http://footballstadiumdigest.com/wp-content/uploads/2016/06/indiana-memorial-stadium.jpg")
indiana.images.create(photo: "https://static1.squarespace.com/static/51d32803e4b07d5c57a6b979/t/5ada22d0758d467764f1dae3/1524245202747/IMG_0508.JPG")
husky = Areana.create(name: "Husky Stadium", capacity: 70500, state: "Washington", city: "Seattle", conference: "Pac 12")
indiana.images.create(photo: "http://image.mlive.com/home/mlive-media/width620/img/wolverines_impact/photo/bloomington-in---20170831---the-ohio-state-2500955204d9f3f6.jpg")
rutgers.images.create(photo: "https://scarletknights.com/images/2017/7/11/HPSS.JPG?width=700&height=700&mode=crop")
rutgers.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Rutgers_Stadium.jpg")
berkeley = Areana.create(name: "California Memorial Stadium", capacity: 62500, state: "California", city: "Berkeley", conference: "Pac 12")
rutgers.images.create(photo: "http://scarletknights.com/images/2016/5/9/11926355.jpeg")
maryland.images.create(photo: "https://cbswashington.files.wordpress.com/2014/10/456647878.jpg?w=1024&h=576&crop=1")
maryland.images.create(photo: "http://nationsgroup.com/img/projects/1416253336.png")
sun_devils = Areana.create(name: "Sun Devil Stadium", capacity: 56000, state: "Arizona", city: "Tempe", conference: "Pac 12")
maryland.images.create(photo: "http://www.huskerbar.com/wp-content/uploads/2014/07/Maryland-Stadium.jpg")
minn.images.create(photo: "http://www.mortenson.com/~/media/images/projects/sports%20and%20event%20centers/tcf%20bank%20stadium/tcf-bank-stadium-12.ashx?h=451&la=en&w=680")
minn.images.create(photo: "https://cdn4.sportngin.com/attachments/photo/1047/6988/TCF_Bank_Stadium_large.jpg")
arizona = Areana.create(name: "Arizona Stadium", capacity: 56000, state: "Arizona", city: "Tucson", conference: "Pac 12")
minn.images.create(photo: "http://umndesigner.wpengine.com/wp-content/uploads/2012/08/tcfstadium1.jpg")
northwestern.images.create(photo: "http://news.medill.northwestern.edu/chicago/wp-content/uploads/sites/3/2015/11/IMG_6845-1038x555.jpg")
northwestern.images.create(photo: "https://aviewfrommyseat.com/thumb/profan9-20170902202446.jpg")
oregon = Areana.create(name: "Autzen Stadium", capacity: 54000, state: "Oregon", city: "Eugene", conference: "Pac 12")
northwestern.images.create(photo: "http://www.laketheposts.com/wp-content/uploads/2013/09/Ryan-Field-gameday.jpg")

usc.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2015/10/USC.DrewCieszynski.jpg")
stanford = Areana.create(name: "Stanford Stadium", capacity: 50500, state: "California", city: "Stanford", conference: "Pac 12")
usc.images.create(photo: "https://news.usc.edu/files/2014/08/Coliseum-upgrades-824x549.jpg")
usc.images.create(photo: "https://photos.smugmug.com/Landscapes/Places/i-3SQKjLc/4/f1406f7a/X2/Tara%27s%20Wedding%20%288%20of%2015%29-X2.jpg")
ucla.images.create(photo: "https://www.discoverlosangeles.com/sites/default/files/styles/article_image/public/media/Sports/100th-rose-bowl-game-stanford-michigan-state.jpg")
colorado = Areana.create(name: "Folsom Field", capacity: 50000, state: "Colorado", city: "Boulder", conference: "Pac 12")
ucla.images.create(photo: "https://www.roadtrips.com/wp-content/uploads/2016/10/rosebowl-hero5.jpg")
ucla.images.create(photo: "https://s3media.247sports.com/Uploads/Assets/519/487/6_5487519.jpg")
husky.images.create(photo: "http://gohuskies.com/common/controls/image_handler.aspx?thumb_id=0&image_path=/images/2016/10/17/9.jpg")
utah = Areana.create(name: "Rice-Eccles Stadium", capacity: 46000, state: "Utah", city: "Salt Lake City", conference: "Pac 12")
husky.images.create(photo: "http://aviewfrommyseat.com/wallpaper/anonymous-20150910123613.jpg")
husky.images.create(photo: "https://render.fineartamerica.com/images/rendered/default/poster/10/8/break/images-medium-5/the-stadium-and-the-lake-max-waugh.jpg")
berkeley.images.create(photo: "http://www.premierpartnerships.com/wp-content/uploads/2014/02/kabam-field.jpg")
oregon_state = Areana.create(name: "Reser Stadium", capacity: 45500, state: "Oregon", city: "Corvallis", conference: "Pac 12")
berkeley.images.create(photo: "https://i.ytimg.com/vi/2bUnEL20hB0/maxresdefault.jpg")
berkeley.images.create(photo: "https://s.hdnux.com/photos/52/63/03/11219148/3/1024x1024.jpg")
sun_devils.images.create(photo: "https://www.signsofthetimes.com/sites/default/files/styles/main_image_750_x_500_/public/editorial/VideoBoard.jpg?itok=vbGKDjQx")
wash_state = Areana.create(name: "Martin Stadium", capacity: 32000, state: "Washington", city: "Pullman", conference: "Pac 12")
sun_devils.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Sun_Devil_Stadium_-_Pac12_Championship.jpg/1200px-Sun_Devil_Stadium_-_Pac12_Championship.jpg")
sun_devils.images.create(photo: "https://secureservercdn.net/3e1.333.godaddywp.com/wp-content/uploads/2017/10/asu-sun-devil-stadium-crop-u41496.jpg")
arizona.images.create(photo: "http://footballstadiumdigest.com/wp-content/uploads/2017/11/Arizona-Stadium.jpg")
arizona.images.create(photo: "https://dbukjj6eu5tsf.cloudfront.net/sidearm.sites/arizona.sidearmsports.com/images/2015/12/15/DLVFCCQFAAUIPIL.20151215222627.jpg")
temple = Areana.create(name: "Lincoln Financial Field", capacity: 68500, state: "Pennsylvania", city: "Philidelphia", conference: "AAC")
arizona.images.create(photo: "http://cdn3.bigcommerce.com/s-n7zrdl/products/12355/images/12707/WSPE_1063_AZ_Tucson_Arizona_Stadium__60405.1431486844.451.416.jpg?c=2")
oregon.images.create(photo: "https://imagesvc.timeincapp.com/v3/mm/image?url=https%3A%2F%2Fcdn-s3.si.com%2Fs3fs-public%2Fstyles%2Fmarquee_large_2x%2Fpublic%2Fimages%2Fautzen-stadium-oregon-ducks-spotlight.jpg%3Fitok%3D_CFWGC1T&w=1100&q=85")
oregon.images.create(photo: "https://res.cloudinary.com/simpleview/image/fetch/c_fill,f_auto,h_452,q_75,w_982/http://res.cloudinary.com/simpleview/image/upload/v1466621977/clients/lanecounty/C6620483F89DF5B74F3BF1F7696AB5F1_3fccd7ef-33ef-43bf-a516-d1a80e26f142.jpg")
usf = Areana.create(name: "Raymond James Stadium", capacity: 66000, state: "Florida", city: "Tampa", conference: "AAC")
oregon.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/102707-Oregon-AutzenStadium-ext.jpg/1200px-102707-Oregon-AutzenStadium-ext.jpg")
stanford.images.create(photo: "http://cdn.fbschedules.com/blog/wp-content/uploads/2015/05/stanford-stadium.jpg")
stanford.images.create(photo: "https://www.rateyourseats.com/shared/Stanford-Stadium-Section-220-Row-J-on-4-11-2015f.jpg")
memphis = Areana.create(name: "Liberty Bowl", capacity: 62000, state: "Tennessee", city: "Memphis", conference: "AAC")
stanford.images.create(photo: "https://i.pinimg.com/originals/10/34/52/103452c2fd1fa6fdfe522ddbea907a6a.jpg")
colorado.images.create(photo: "http://fightmusic.com/wallpapers/pac12/PAC-12_Colorado__Folsom_Field__1920x1200.jpg")
colorado.images.create(photo: "https://business-news.ucdenver.edu/wp-content/uploads/2017/09/TIWNCAAFoct04.png")
east_car = Areana.create(name: "Dowdy Ficklen Stadium", capacity: 50000, state: "North Carolina", city: "Greenville", conference: "AAC")
colorado.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/1/14/Folsom_field.jpg")
utah.images.create(photo: "https://stadium.utah.edu/wp-content/uploads/2018/02/Stadium1.jpg")
utah.images.create(photo: "http://utahutes.com/images/2016/6/13/rice_eccles_stadium_Cal_10_10_15.jpg")
ucf = Areana.create(name: "Spectrum Stadium", capacity: 44000, state: "Florida", city: "Orlando", conference: "AAC")
utah.images.create(photo: "https://vignette.wikia.nocookie.net/estadios/images/8/81/Riceeccles.jpg/revision/latest?cb=20160429192408&path-prefix=es")
oregon_state.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Hawaii_9_13_08_pano2.jpg/800px-Hawaii_9_13_08_pano2.jpg")
oregon_state.images.create(photo: "https://www.nbcsports.com/northwest/sites/csnnw/files/2017/02/01/oregonstatebeavers-reserstadium.jpg")
houston = Areana.create(name: "TDECU Stadium", capacity: 40000, state: "Texas", city: "Houston", conference: "AAC")
oregon_state.images.create(photo: "https://www.kpff.com/portfoliov2-files/reser-stadium/reserstadium_portlandstructural_4.jpg")
wash_state.images.create(photo: "http://admin.wsucougars.com/images/2016/8/30/Martin_Stadium.jpg")
wash_state.images.create(photo: "http://admin.wsucougars.com/images/2016/6/21//MartinStadium2014_017_fix.jpg?width=1000&height=355&mode=crop")
cincy = Areana.create(name: "Nippert Stadium", capacity: 40000, state: "Ohio", city: "Cincinnati", conference: "AAC")
wash_state.images.create(photo: "http://wsucougars.com/images/2014/12/23/RAHNFXWHOMEEKVM.20141223021316.jpg")

temple.images.create(photo: "http://footballstadiumdigest.com/wp-content/uploads/2015/10/temple-linc.jpg")
uconn = Areana.create(name: "Rentschler Field", capacity: 40000, state: "Connecticut", city: "East Hartford", conference: "AAC")
temple.images.create(photo: "https://c1.staticflickr.com/7/6163/6166421084_9f68411c96_b.jpg")
temple.images.create(photo: "https://images.gametime.co/sport/cfb/gametime-images/cfbtem/hero@4x/temple-football.jpg?auto=webp&format=pjpg&quality=80&disable=upscale&dpr=1&fit=crop&width=1040&height=520")
usf.images.create(photo: "https://gousfbulls.com/images/2005/12/13/JDBHMJDIZYMTTBQ.20051213004106.jpg?width=1024&height=576&mode=crop")
navy = Areana.create(name: "Navy-Marine Corps Memorial Stadium", capacity: 34000, state: "Maryland", city: "Annapolis", conference: "AAC")
usf.images.create(photo: "https://gousfbulls.com/images/2009/10/28/PEZPMGUYRYSWXVU.20091028161650.jpg?width=1024&height=576&mode=crop")
usf.images.create(photo: "http://blogs.mycentraljersey.com/rutgers/files/2012/09/RJS.jpg")
memphis.images.create(photo: "https://www.tigerbookstore.com/v/vspfiles/assets/images/Memphis%20Tigers%20Liberty%20Bowl%20Stadium2.jpg")
smu = Areana.create(name: "Gerald J. Ford Stadium", capacity: 32000, state: "Texas", city: "University Park", conference: "AAC")
memphis.images.create(photo: "https://i.pinimg.com/originals/10/5e/8c/105e8c344195e7b06724ccc5e98c5ba2.jpg")
memphis.images.create(photo: "http://www.colliervillephoto.com/liberty-bowl-memphis.jpg")
east_car.images.create(photo: "https://ecupirates.com/images/2016/6/27/Dowdy_Ficklen.jpg?width=1000&height=563&mode=crop")
tulane = Areana.create(name: "Yulman Stadium", capacity: 30000, state: "Louisiana", city: "New Orleans", conference: "AAC")
east_car.images.create(photo: "https://pbs.twimg.com/media/CrjNp-PWIAUqRpl.jpg")
east_car.images.create(photo: "https://d3e1o4bcbhmj8g.cloudfront.net/photos/479680/huge/bc35a0232560f1944795ff5d0996d555d990d920.jpg")
ucf.images.create(photo: "http://ucfknights.com/images/2016/8/15/ucfFBusc_5271.jpg")
tulsa = Areana.create(name: "H.A. Chapman Stadium", capacity: 30000, state: "Oklahoma", city: "Tulsa", conference: "AAC")
ucf.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Spectrum_Stadium_-_2017_AAC_Championship_Game.jpg/1200px-Spectrum_Stadium_-_2017_AAC_Championship_Game.jpg")
ucf.images.create(photo: "https://hbcusports.com/wp-content/uploads/2014/03/brighthouse-stadium-ucf.jpg")
houston.images.create(photo: "http://www.uh.edu/magazine/14f/images/photo-tdecu-stadium.jpg")
houston.images.create(photo: "https://s.hdnux.com/photos/31/70/76/6786968/3/920x920.jpg")
notre_dame = Areana.create(name: "Notre Dame Stadium", capacity: 77500, state: "Indiana", city: "South Bend", conference: "Independent")
houston.images.create(photo: "http://1c71hb3in51z3g8k1j1nogrdvsm.wpengine.netdna-cdn.com/wp-content/uploads/2016/11/UHvLouisville-29-620x414.jpg")
cincy.images.create(photo: "https://imagesvc.timeincapp.com/v3/fan/image?url=https%3A%2F%2Fcincyontheprowl.com%2Ffiles%2F2014%2F04%2Fncaa-football-purdue-cincinnati.jpg&c=sc&w=850&h=560")
cincy.images.create(photo: "https://gobearcats.com/images/2017/6/19/ucats_16_fb_main.jpg?width=700&height=700&mode=crop")
byu = Areana.create(name: "LaVell Edwards Stadium", capacity: 63500, state: "Utah", city: "Provo", conference: "Independent")
cincy.images.create(photo: "https://i.ytimg.com/vi/ZvHcwYnn-iw/maxresdefault.jpg")
uconn.images.create(photo: "https://xflbuzz.files.wordpress.com/2018/02/uconn-rentschler-field-university-of-connecticut.jpg")
uconn.images.create(photo: "http://www.trbimg.com/img-55a7f88b/turbine/hc-rentschler-stadiumn-pratt-naming-0717-20150716")
army = Areana.create(name: "Michie Stadium", capacity: 38000, state: "New York", city: "West Point", conference: "Independent")
uconn.images.create(photo: "https://www.cbssports.com/images/collegefootball/uspw_5624008.jpg")
navy.images.create(photo: "http://www.trbimg.com/img-592b0264/turbine/ph-ac-cs-capitals-navy-game-0529-20170528")
navy.images.create(photo: "https://vignette.wikia.nocookie.net/armchair-new/images/4/49/Navy-Marine_Corps_Memorial_Stadium.jpg/revision/latest?cb=20100906153902")
newmex_st = Areana.create(name: "Aggie Memorial Stadium", capacity: 30000, state: "New Mexico", city: "Las Cruces", conference: "Independent")
navy.images.create(photo: "http://e28015e90a1c21a23cb5-0e0f033f94971301dcd586c7db7e66e0.r36.cf5.rackcdn.com/Navy-Marine%20Stadium/93c5a3eb82bf7eaa0f3bafa698df09fc.jpg")
smu.images.create(photo: "https://visitdallas-sv.imgix.net/c_fit,w_800,h_600/crm/dallas/Ford_Stadium_83013_0200_5ec8c959-5056-b3a8-49ed1260b1b6cdf7.jpg?w=800&h=600&fit=crop&crop=entropy,faces&q=60&fm=pjpg&auto=compress,enhance,format,redeye&trim=auto")
smu.images.create(photo: "https://i1.wp.com/supertailgate.com/wp-content/uploads/2016/11/SMU2-e1481910636349.jpg?fit=700%2C403&ssl=1")
umass = Areana.create(name: "Warren McGuirk Alumni Stadium", capacity: 17000, state: "Massachusetts", city: "Hadley", conference: "Independent")
smu.images.create(photo: "https://www.smu.edu/-/media/Images/News/CampusBuildings/4508648.jpg?la=en")
tulane.images.create(photo: "https://bloximages.newyork1.vip.townnews.com/theadvocate.com/content/tncms/assets/v3/editorial/e/af/eafc5d88-1766-50d1-867d-0f751678dc1a/5751826aae99a.image.jpg")
tulane.images.create(photo: "http://media.nola.com/tulane_impact/photo/tech-football-tulane-hosts-georgia-tech-at-new-yulman-stadium-2becc37284234842.jpg")
tulane.images.create(photo: "https://twt-thumbs.washtimes.com/media/image/2014/09/05/f533569af0d9de225e0f6a7067005fcb_c0-179-3264-2082_s885x516.jpg?bd2669ee51ad61ce489061e519b9e38a1feeaa85")
tulsa.images.create(photo: "https://i.pinimg.com/originals/b5/1e/6c/b51e6c797878c9d3362eaf722b80cece.jpg")
uab = Areana.create(name: "Legion Field", capacity: 71500, state: "Alabama", city: "Birmingham", conference: "Conference USA")
tulsa.images.create(photo: "https://i.pinimg.com/originals/b8/8c/7e/b88c7e3af0fa1137b0cc418faa47efad.jpg")
tulsa.images.create(photo: "https://www.jedunn.com/sites/default/files/HA%20Chapman%20Staduim_aerial%2009%20copy.jpg")

utsa = Areana.create(name: "Alamodome", capacity: 65000, state: "Texas", city: "San Antonio", conference: "Conference USA")
notre_dame.images.create(photo: "https://www.uhnd.com/wp-content/uploads/2007/05/notre-dame-stadium-1-816x460.jpg")
notre_dame.images.create(photo: "http://www.musco.com/wp-content/uploads/2017/02/Notre-Dame-1200x600.jpg")
notre_dame.images.create(photo: "https://static.giantbomb.com/uploads/original/0/46/1834966-nd.jpg")
utep = Areana.create(name: "Sun Bowl", capacity: 51500, state: "Texas", city: "El Paso", conference: "Conference USA")
byu.images.create(photo: "https://vignette.wikia.nocookie.net/byufootball/images/e/ef/Stadium.jpg/revision/latest?cb=20120201010255")
byu.images.create(photo: "https://davd.photo/wp-content/uploads/2014/09/dusk-settles-over-byu-vs-houston.jpg")
byu.images.create(photo: "https://res.cloudinary.com/simpleview/image/upload/crm/utahvalley/BYU-Stadium-0cb050145056a36_0cb0517e-5056-a36a-0b92656ddffa97de.jpg")
rice = Areana.create(name: "Rice Stadium", capacity: 47000, state: "Texas", city: "Houston", conference: "Conference USA")
army.images.create(photo: "http://wac.b63f.edgecastcdn.net/80B63F/goarmywestpoint-com/images/2015/10/12/Michie_Stadium_10102015_0067.jpg")
army.images.create(photo: "https://stadiumsandarenas.files.wordpress.com/2009/06/844.jpg")
army.images.create(photo: "https://i1.wp.com/forwhattheygaveonsaturdayafternoon.com/photos/michie-td.jpg")
marshall = Areana.create(name: "Joan C. Edwards Stadium", capacity: 38000, state: "West Virginia", city: "Huntington", conference: "Conference USA")
newmex_st.images.create(photo: "http://i2.wp.com/nmsu.documentaryshooters.com/wp-content/uploads/2014/10/DSC_0210.jpg")
newmex_st.images.create(photo: "https://s3-media1.fl.yelpcdn.com/bphoto/A6ipZlfzdU8B80IMp6IhUA/l.jpg")
newmex_st.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Aggie_Memorial_Stadium_-_West_Side_Stands_%26_Press_Box_01.JPG/1200px-Aggie_Memorial_Stadium_-_West_Side_Stands_%26_Press_Box_01.JPG")
southern_miss = Areana.create(name: "M.M. Roberts Stadium", capacity: 36000, state: "Mississippi", city: "Hattiesburg", conference: "Conference USA")
umass.images.create(photo: "http://www.bostonherald.com/sites/default/files/styles/gallery/public/media/2017/08/23/082217mcquirk.jpg?itok=2v95oxvP")
umass.images.create(photo: "http://3.bp.blogspot.com/-pIM0xlq6k4k/ViOsHkwYglI/AAAAAAAAQ00/GMpmhoKcXtw/s1600/mcguirk_IMG_20151017_153612718.jpg")
umass.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2014/10/UMass2.jpg")
mid_tenn = Areana.create(name: "Johnny Red Floyd Stadium", capacity: 31000, state: "Tennessee", city: "Murfreesboro", conference: "Conference USA")


uab.images.create(photo: "https://uabsports.com/images/2011/10/27/legion_field_630x250.jpg")
north_texas = Areana.create(name: "Apogee Stadium", capacity: 31000, state: "Texas", city: "Denton", conference: "Conference USA")
uab.images.create(photo: "https://image.al.com/home/bama-media/width620/img/sports_impact/photo/15842140-mmmain.jpg")
uab.images.create(photo: "http://media.al.com/sports_impact/photo/alabama-am-vs-uab-football-a1f1b8393cb8aa18.jpg")
utsa.images.create(photo: "http://s3.amazonaws.com/sidearm.sites/utsa.sidearmsports.com/images/2014/9/10/GLEVNTGAQCIERJW.20140910175042.jpg")
fau = Areana.create(name: "FAU Stadium", capacity: 30000, state: "Florida", city: "Boca Raton", conference: "Conference USA")
utsa.images.create(photo: "http://www.alamodome.com/assets/img/UTSA_Football_Slide-ac6d4cc60d.jpg")
utsa.images.create(photo: "http://s3.amazonaws.com/sidearm.sites/utsa.sidearmsports.com/images/2015/10/9/YJRHWBPYZANQNQA.20151009174856.jpg")
utep.images.create(photo: "https://i1.wp.com/supertailgate.com/wp-content/uploads/2016/11/UTEP2-1-e1484915006888.jpg?fit=700%2C399&ssl=1")
latech = Areana.create(name: "Joe Aillet Stadium", capacity: 28500, state: "Louisiana", city: "Ruston", conference: "Conference USA")
utep.images.create(photo: "http://static-16.sinclairstoryline.com/resources/media/a6f24923-4bdc-46ad-92ba-2913d3cd3cae-large16x9_UTEPstadium.jpg?1473099308314")
utep.images.create(photo: "https://bloximages.newyork1.vip.townnews.com/elpasoinc.com/content/tncms/assets/v3/editorial/5/e9/5e9a490a-bd02-11e3-9bd2-001a4bcf6878/534069fa932f0.image.jpg")
rice.images.create(photo: "https://postinspostcards.files.wordpress.com/2012/09/rice-stadium_2.jpg")
fiu = Areana.create(name: "Riccardo Silva Stadium", capacity: 23500, state: "Florida", city: "Miami", conference: "Conference USA")
rice.images.create(photo: "https://c1.staticflickr.com/4/3256/3093598517_ebb8b9c015_b.jpg")
rice.images.create(photo: "https://s.hdnux.com/photos/06/33/13/1684167/3/920x920.jpg")
marshall.images.create(photo: "http://static.panoramio.com/photos/large/112149174.jpg")
west_kentucky = Areana.create(name: "L.T. Smith Stadium", capacity: 22000, state: "Kentucky", city: "Bowling Green", conference: "Conference USA")
marshall.images.create(photo: "https://cdn-s3.si.com/s3fs-public/styles/marquee_large_2x/public/2016/05/31/marshall-football-dave-dunn.jpg?itok=uIq49PTe")
marshall.images.create(photo: "http://mediad.publicbroadcasting.net/p/wvpn/files/styles/medium/public/201607/marshall_stadium.jpg")
southern_miss.images.create(photo: "https://i.pinimg.com/originals/71/5d/00/715d00a2331a70e34ac7a062ae8bd3ed.jpg")
old_dom = Areana.create(name: "S.B. Ballard Stadium", capacity: 20000, state: "Virginia", city: "Norfolk", conference: "Conference USA")
southern_miss.images.create(photo: "https://www.usm.edu/sites/default/files/admissions/gallery/photo-gallery-spirit/south-endzone-football.jpg")
southern_miss.images.create(photo: "https://i.pinimg.com/originals/fd/4c/1e/fd4c1e2791679b3cb8e0bef430878b0f.jpg")
mid_tenn.images.create(photo: "https://goblueraiders.com/common/controls/image_handler.aspx?thumb_id=0&image_path=/images/2014/7/16/FloydMainPic.jpg")
charlotte = Areana.create(name: "Jerry Richardson Stadium", capacity: 15000, state: "North Carolina", city: "Charlotte", conference: "Conference USA")
mid_tenn.images.create(photo: "http://collegefootballtour.com/wp-content/uploads/2012/05/floydstadium2.jpg")
mid_tenn.images.create(photo: "https://i.pinimg.com/originals/40/c8/6a/40c86a528aa483acb24b63c56fdd662a.jpg")
north_texas.images.create(photo: "https://www.unt.edu/sites/default/files/16_637_footballsmu0635a_story.jpg")
north_texas.images.create(photo: "https://nmgprod.s3.amazonaws.com/media/filer_public_thumbnails/filer_public/52/b4/52b47947-ef28-4ecd-a62b-75ae6251810d/apogee2.jpg__640x360_q85_crop_subsampling-2.jpg")
cmu = Areana.create(name: "Kelly/Shorts Stadium", capacity: 30000, state: "Michigan", city: "Mount Pleasant", conference: "MAC")
north_texas.images.create(photo: "http://www.sturdisteel.com/wp-content/uploads/2014/01/University-of-North-Texas-Apogee-Stadium.jpg")
fau.images.create(photo: "https://www.upressonline.com/wp-content/uploads/2016/04/FAU-v.-UM_Max-Jackson_002-900x601.jpg")
fau.images.create(photo: "https://www.palmbeachpost.com/rf/image_large/Pub/p5/PalmBeachPost/2014/12/14/Images/photos.medleyphoto.6538308.jpg")
eastern_mich = Areana.create(name: "Rynearson Stadium", capacity: 30000, state: "Michigan", city: "Ypsilanti", conference: "MAC")
fau.images.create(photo: "https://i2.wp.com/www.millerlegg.com/wp-content/uploads/2015/11/FAU-Stadium-5.jpg?fit=960%2C768")
latech.images.create(photo: "http://img.bleacherreport.net/img/images/photos/001/638/460/Stadium_crop_north.jpg?1333386621&w=630&h=420")
latech.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2017/11/Joe-Aillet-Stadium-Interior.jpg")
wmu = Areana.create(name: "Waldo Stadium", capacity: 30000, state: "Michigan", city: "Kalamazoo", conference: "MAC")
latech.images.create(photo: "http://www.louisianahelicam.com/img/s/v-3/p1450498381-4.jpg")
fiu.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2017/11/Stadium-interior-900x600.jpg")
fiu.images.create(photo: "http://fiusports.typepad.com/.a/6a0134865674e5970c0147e3b18266970b-pi")
akron = Areana.create(name: "InfroCision Stadium", capacity: 30000, state: "Ohio", city: "Akron", conference: "MAC")
fiu.images.create(photo: "https://upload.wikimedia.org/wikipedia/en/b/bc/FIU_Duke_2011.jpg")
west_kentucky.images.create(photo: "https://imagesvc.timeincapp.com/v3/fan/image?url=https%3A%2F%2Fbluegrassdominion.com%2Ffiles%2F2014%2F10%2Fncaa-football-bowling-green-western-kentucky.jpg&c=sc&w=850&h=560")
west_kentucky.images.create(photo: "https://postinspostcards.files.wordpress.com/2014/09/1601044_897188626977364_5577164084287119228_n.jpg")
buffalo = Areana.create(name: "UB Stadium", capacity: 29000, state: "New York", city: "Buffalo", conference: "MAC")
west_kentucky.images.create(photo: "http://www.stadiumbleachers.com/images/portfolio/5E9052DED38DF1E0516E8273.JPG")
old_dom.images.create(photo: "http://www.sbballard.com/CropUp/-x525/media/1215/SB-Stadium-Gallery-6.jpg")
old_dom.images.create(photo: "http://www.eyesofsilverblue.com/wp-content/uploads/2012/04/4-IMG_2642.jpg")
toledo = Areana.create(name: "Glass Bowl", capacity: 26000, state: "Ohio", city: "Toledo", conference: "MAC")
old_dom.images.create(photo: "https://vignette.wikia.nocookie.net/collegefootballmania/images/8/84/Foreman_Field.jpg/revision/latest?cb=20150121065355")
charlotte.images.create(photo: "https://d2j8c2rj2f9b78.cloudfront.net/uploads/poster-images/Jerry-Richardson-Stadium.jpeg")
charlotte.images.create(photo: "http://image.cdnllnwnl.xosnetwork.com/pics32/640/SI/SIBMFCHNICBNDCE.20130221191333.jpg")
kent = Areana.create(name: "Dix Stadium", capacity: 25000, state: "Ohio", city: "Kent", conference: "MAC")
charlotte.images.create(photo: "https://tud1explore.files.wordpress.com/2012/10/unc-charlotte-jerry-richardson-stadium.jpg")

cmu.images.create(photo: "http://grfx.cstv.com/schools/cmu/graphics/football-facility-hdr-18.jpg")
miami_ohio = Areana.create(name: "Fred C. Yager Stadium", capacity: 24000, state: "Ohio", city: "Oxford", conference: "MAC")
cmu.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Kelly_Shorts_Stadium.jpg/1200px-Kelly_Shorts_Stadium.jpg")
cmu.images.create(photo: "https://tour.cmich.edu/images/IMG_2013081543960_DETL.jpg")
eastern_mich.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2016/09/Grey-Field-at-Rynearson-Stadium-900x675.jpg")
bowling_green = Areana.create(name: "Doyt L. Perry Stadium", capacity: 24000, state: "Ohio", city: "Bowling Green", conference: "MAC")
eastern_mich.images.create(photo: "http://s3.amazonaws.com/emueagles.com/images/2014/8/4/Factory.jpg")
eastern_mich.images.create(photo: "http://mediad.publicbroadcasting.net/p/wemu/files/styles/medium/public/201604/Rynearsonwide-B-121107.jpg")
wmu.images.create(photo: "https://wmubroncos.com/images/2016/8/2/Waldo_Stadium_2.jpg")
ohio_stad = Areana.create(name: "Peden Stadium", capacity: 24000, state: "Ohio", city: "Athens", conference: "MAC")
wmu.images.create(photo: "https://wmubroncos.com/images/2016/8/1/Packed_Waldo.jpg?width=1000&height=563&mode=crop")
wmu.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2016/11/West4.jpg")
akron.images.create(photo: "https://i.ytimg.com/vi/d3wL-P8ak1E/maxresdefault.jpg")
nui = Areana.create(name: "Huskie Stadium", capacity: 23500, state: "Illinois", city: "DeKalb", conference: "MAC")
akron.images.create(photo: "http://www.skylinepictures.com/University_of_Akron_uak2_large_DM.jpg")
akron.images.create(photo: "https://i.pinimg.com/originals/e9/b9/75/e9b975462d2d2a7012b614745b24f7bb.jpg")
buffalo.images.create(photo: "http://aviewfrommyseat.com/wallpaper/MountaindewPSU-20140925132300.jpg")
ball_st = Areana.create(name: "Scheumann Stadium", capacity: 22500, state: "Indiana", city: "Muncie", conference: "MAC")
buffalo.images.create(photo: "http://www.ubfootballcamps.com/images/stadium-3X5A2264.jpg")
buffalo.images.create(photo: "http://www.aturf.com/wp-content/uploads/2016/07/UB-Alumni-Stadium-Field.jpg")
toledo.images.create(photo: "http://www.toledoblade.com/image/2015/06/12/600x600_cB/n7glass.jpg")
toledo.images.create(photo: "https://res-5.cloudinary.com/rivals/image/upload/t_large/wmj0qct67n52g0whprca")
sdsu = Areana.create(name: "SDCCU Stadium", capacity: 70500, state: "California", city: "San Diego", conference: "Mountain West")
toledo.images.create(photo: "http://www.coachtk.com/images/actionShots/glassbowl2.jpg")
kent.images.create(photo: "https://imagesvc.timeincapp.com/v3/mm/image?url=https%3A%2F%2Fcdn-s3.si.com%2Fs3fs-public%2Fstyles%2Fmarquee_large_2x%2Fpublic%2F2014%2F08%2F28%2Fkent-state-golden-flashes-ohio-bobcats-watch-online.jpg%3Fitok%3DFTCb-I-L&w=1100&q=85")
kent.images.create(photo: "http://crossfitmassillon.com/wp-content/uploads/2015/05/20150524_113035-940x500.jpg")
hawaii = Areana.create(name: "Aloha Stadium", capacity: 50000, state: "Hawaii", city: "Honolulu", conference: "Mountain West")
kent.images.create(photo: "https://i.ytimg.com/vi/hJ0QgAhxZB4/maxresdefault.jpg")
miami_ohio.images.create(photo: "http://www.coachchuckmartin.com/gallery/yager-stadium_gallery_1396215157.jpg")
miami_ohio.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/5/50/Yager_Stadium_%2823656930573%29.jpg")
airforce = Areana.create(name: "Falcon Stadium", capacity: 46500, state: "Colorado", city: "Colorado Springs", conference: "Mountain West")
miami_ohio.images.create(photo: "http://www.coachchuckmartin.com/gallery/yager-stadium_gallery_1397071266.jpg")
bowling_green.images.create(photo: "https://i.pinimg.com/originals/27/29/c0/2729c0ad00062c2b0182a4bd38060bad.jpg")
bowling_green.images.create(photo: "http://fightmusic.com/wallpapers/mac/MAC_Bowling_Green__Doyt_Perry_Stadium__1280x800.jpg")
colorado_st = Areana.create(name: "Colorado State Stadium", capacity: 41000, state: "Colorado", city: "Fort Collins", conference: "Mountain West")
bowling_green.images.create(photo: "https://i.pinimg.com/originals/4c/83/f1/4c83f125c54880b966810834091201fe.jpg")
ohio_stad.images.create(photo: "http://bridge.jo/wp-content/uploads/2016/12/Pedenstadium01_1300.jpg")
ohio_stad.images.create(photo: "https://calendarmedia.blob.core.windows.net/assets/7b293970-1b71-425d-9306-398af63c0341.jpg")
fresno_st = Areana.create(name: "Bulldog Stadium", capacity: 41000, state: "California", city: "Fresno", conference: "Mountain West")
ohio_stad.images.create(photo: "http://grfx.cstv.com/schools/ohio/graphics/peden-2.jpg")
nui.images.create(photo: "https://i0.wp.com/footballscoop.com/wp-content/uploads/2014/10/Huskie-Stadium.jpg")
nui.images.create(photo: "https://www.enjoyillinois.com/assets/Tourism-Operators/images/IMG-4255.jpg")
new_mex = Areana.create(name: "Dreamstyle Stadium", capacity: 39000, state: "New Mexico", city: "Albuquerque", conference: "Mountain West")
nui.images.create(photo: "http://www.daily-chronicle.com/_internal/cimg!0/nfx6d3a1qq73vuoqjpxai2xc0sg4wni")
ball_st.images.create(photo: "https://ballstatesports.com/images/2018/1/24/stadium0909.jpg")
ball_st.images.create(photo: "http://image.cdnllnwnl.xosnetwork.com/pics14/640/RW/RWRRMJPLUWHQYVE.20071116213643.jpg")
unlv = Areana.create(name: "Sam Boyd Stadium", capacity: 37000, state: "Nevada", city: "Whitney", conference: "Mountain West")
ball_st.images.create(photo: "https://pbs.twimg.com/media/C-TQk94XgAExW18.jpg")

sdsu.images.create(photo: "http://www.trbimg.com/img-5b028024/turbine/sd-sp-aztecs-football-friends-sdsu-west-soccercity-stadium-20180520")
boise_st = Areana.create(name: "Albertsons Stadium", capacity: 36000, state: "Idaho", city: "Boise", conference: "Mountain West")
sdsu.images.create(photo: "http://ollie.neglerio.com/wp-content/uploads/2011/09/aztecs-kgb-skyshow-1.jpg")
sdsu.images.create(photo: "http://footballstadiumdigest.com/wp-content/uploads/2017/03/SDSU-football.jpg")
hawaii.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Alohastadium.jpg/1200px-Alohastadium.jpg")
sjsu = Areana.create(name: "CEFCU Stadium", capacity: 30500, state: "California", city: "San Jose", conference: "Mountain West")
hawaii.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2017/11/Aloha-Stadium-Interior.jpg")
hawaii.images.create(photo: "http://hawaiiathletics.com/common/controls/image_handler.aspx?thumb_id=0&image_path=/images/2015/7/21/Aloha_Stadium_top_936.jpg")
airforce.images.create(photo: "http://grfx.cstv.com/schools/afa/graphics/afa-15-falcon-stadium2.jpg")
wyoming = Areana.create(name: "War Memorial Stadium", capacity: 29000, state: "Wyoming", city: "Laramie", conference: "Mountain West")
airforce.images.create(photo: "https://cdn.csgazette.biz/cache/r960-d4fd0aa763311dec04b42387499b35e2.jpg")
airforce.images.create(photo: "https://media.defense.gov/2013/May/29/2000045827/-1/-1/0/130529-F-ZJ145-732.JPG")
colorado_st.images.create(photo: "https://blogs-images.forbes.com/kristidosh/files/2017/08/IMAG8745.jpg")
nevada = Areana.create(name: "Mackay Stadium", capacity: 26000, state: "Nevada", city: "Reno", conference: "Mountain West")
colorado_st.images.create(photo: "https://source.colostate.edu/wp-content/uploads/2015/12/option1.jpg")
colorado_st.images.create(photo: "https://thespun.com/wp-content/uploads/2018/04/coloradostatefootballstadium-775x465.png")
fresno_st.images.create(photo: "http://gobulldogs.com/images/2016/8/5/7381537.jpeg")
utah_st = Areana.create(name: "Maverik Stadium", capacity: 25500, state: "Utah", city: "Logan", conference: "Mountain West")
fresno_st.images.create(photo: "https://i.pinimg.com/originals/82/74/33/82743392f68e8f673efb0c8ad0152e20.jpg")
fresno_st.images.create(photo: "http://mccaffreyhomes.info/blog/wp-content/uploads/2014/07/Bulldog-Stadium-Aerial.jpg")
new_mex.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Branch_Field_at_University_Stadium.png/1200px-Branch_Field_at_University_Stadium.png")
new_mex.images.create(photo: "https://unmtickets.com/wp-content/themes/unmtickets/img/Seatviews/FBS/GA.jpg")
cajun = Areana.create(name: "Cajun Field", capacity: 41500, state: "Louisiana", city: "Lafayette", conference: "Sun Belt")
new_mex.images.create(photo: "https://unmtickets.com/wp-content/themes/unmtickets/img/Seatviews/FBS/HH.jpg")
unlv.images.create(photo: "https://www.unlv.edu/sites/default/files/styles/920_width/public/building_images/SBS-D65868_134.jpg?itok=vhShDdfe")
unlv.images.create(photo: "https://www.reviewjournal.com/wp-content/uploads/2013/12/web1_8206919-4-150007_0.jpg")
s_bama = Areana.create(name: "Ladd-Peebles Stadium", capacity: 40000, state: "Alabama", city: "Mobile", conference: "Sun Belt")
unlv.images.create(photo: "https://www.reviewjournal.com/wp-content/uploads/2016/02/1003564505_fbc_unlv_0912_11_3.jpg")
boise_st.images.create(photo: "http://grfx.cstv.com/photos/schools/bosu/sports/m-footbl/auto_original/8194018.jpeg")
boise_st.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2014/12/Operation-Sports.jpg")
app_st = Areana.create(name: "Kidd Brewer Stadium", capacity: 35000, state: "North Carolina", city: "Boone", conference: "Sun Belt")
boise_st.images.create(photo: "https://cdn.cnn.com/cnnnext/dam/assets/111102031400-college-football-stadiums-tl-boise-state-horizontal-large-gallery.jpg")
sjsu.images.create(photo: "https://i.ytimg.com/vi/WA2iwERVi8E/maxresdefault.jpg")
sjsu.images.create(photo: "https://i.ytimg.com/vi/xf6DdLdbD5E/maxresdefault.jpg")
arkansas_st = Areana.create(name: "Centennial Bank Stadium", capacity: 31000, state: "Arkansas", city: "Jonesboro", conference: "Sun Belt")
sjsu.images.create(photo: "https://stadiumjourney.com/wp-content/uploads/2017/08/SJSTate1-900x600.jpg")
wyoming.images.create(photo: "http://res.cloudinary.com/sweetwaternow-com/image/upload/v1462315641/1918277_107227645968340_5590867_n_euh2iu.jpg")
wyoming.images.create(photo: "http://static.panoramio.com/photos/original/2647379.jpg")
la_monroe = Areana.create(name: "Malone Stadium", capacity: 30500, state: "Louisiana", city: "Monroe", conference: "Sun Belt")
wyoming.images.create(photo: "https://collegian.com/wp-content/uploads/2016/09/BorderWar-1024x448.jpg")
nevada.images.create(photo: "http://mediad.publicbroadcasting.net/p/kunr/files/201602/mackaystadium.jpg")
nevada.images.create(photo: "https://www.unr.edu/Images/facilities/main-photos/mackaystadium.jpg")
troy = Areana.create(name: "Veterans Memorial Stadium", capacity: 30500, state: "Alabama", city: "Troy", conference: "Sun Belt")
nevada.images.create(photo: "https://c1.staticflickr.com/5/4009/5078812483_361b91d90a_b.jpg")
utah_st.images.create(photo: "https://www.rentcollegepads.com/blog/wp-content/uploads/2017/01/Utah-fb-field.jpg")
utah_st.images.create(photo: "http://blogs.mercurynews.com/sjsu/files/2015/07/6752063.jpeg")
texas_st = Areana.create(name: "Bobcat Stadium", capacity: 30000, state: "Texas", city: "San Marcos", conference: "Sun Belt")
utah_st.images.create(photo: "https://www.enr.com/ext/resources/Issues/National_Issues/2017/10-Oct/23-Oct/1---USU-Stadium.jpg?1508436298")

cajun.images.create(photo: "https://ragincajuns.com/common/controls/image_handler.aspx?thumb_id=13&image_path=/images/2015/1/15/UL_vs_Southern_2014_Arial_Photo.jpg")
georgia_southern = Areana.create(name: "Allen E. Paulson Stadium", capacity: 25000, state: "Georgia", city: "Statesboro", conference: "Sun Belt")
cajun.images.create(photo: "https://cdn.boydsbets.com/wp-content/uploads/Lafayette-Texas-St-e1507586672479.jpg")
cajun.images.create(photo: "https://louisiana.edu/sites/louisiana/files/news-images/2013-04/stadium%20fisheye.jpg")
s_bama.images.create(photo: "https://s3media.247sports.com/Uploads/Assets/992/905/6_4905992.jpg")
georgia_st = Areana.create(name: "Georgia State Stadium", capacity: 25000, state: "Georgia", city: "Atlanta", conference: "Sun Belt")
s_bama.images.create(photo: "http://media.al.com/live/photo/ladd-stadiumjpg-dc81b9721d46959f.jpg")
s_bama.images.create(photo: "http://media.al.com/sports_impact/photo/posterframejpg-1a9c8e371e527e82.jpg")
app_st.images.create(photo: "https://www.hcpress.com/img/Stadium.jpg")
coastal_car = Areana.create(name: "Brooks Stadium", capacity: 15000, state: "South Carolina", city: "Conway", conference: "Sun Belt")
app_st.images.create(photo: "http://image.cdnl3.xosnetwork.com/pics24/0/PK/PKSOQYUMEXGTNCZ.20091001201315.jpg")
app_st.images.create(photo: "http://image.cdnllnwnl.xosnetwork.com/pics21/800/RH/RHPDYAHLOHAHIGG.20100203183022.jpg")
arkansas_st.images.create(photo: "http://collegefootballtour.com/wp-content/uploads/2016/09/ASU4.jpg")
arkansas_st.images.create(photo: "http://amppob.com/wp-content/uploads/2015/07/Centennial-Bank-Stadium-3.jpg")
arkansas_st.images.create(photo: "https://s-media-cache-ak0.pinimg.com/originals/b9/cf/94/b9cf9416299feae85ee5a67836b99b6d.jpg")
la_monroe.images.create(photo: "https://ulmwarhawks.com/images/2017/3/17/PRRNDTONVMMQZRC.20170317154845.jpg?width=1024&height=576&mode=crop")
la_monroe.images.create(photo: "http://1130thetiger.com/files/2014/08/ulm-football-630x630.jpg?w=980&q=75")
la_monroe.images.create(photo: "https://ulmwarhawks.com/images/2008/8/12/YAHHVSRJQGDWNZQ.20080812164822.jpg?width=1024&height=576&mode=crop")
troy.images.create(photo: "https://troytrojans.com/images/2016/9/23/Veterans_Memorial_Stadium.jpg?width=1000&height=563&mode=crop")
troy.images.create(photo: "http://i57.photobucket.com/albums/g224/nhs_bandgeek07/SBHDISRZYQXJRWP20080314125657.jpg")
troy.images.create(photo: "http://www.nealbrownfootballcamps.com/images/Slide17-1.jpg")
texas_st.images.create(photo: "https://www.athleticbusiness.com/images/gallery/slideshow/11_bobcatstadium2.jpg")
texas_st.images.create(photo: "https://i.ytimg.com/vi/qLJTgN1_ewo/maxresdefault.jpg")
texas_st.images.create(photo: "http://www.oconnellrobertson.com/uploads/images/TxState%20NSCforweb.jpg")
georgia_southern.images.create(photo: "https://upload.wikimedia.org/wikipedia/commons/0/03/Expanded_Paulson_Stadium.jpg")
georgia_southern.images.create(photo: "https://gseagles.com/common/controls/image_handler.aspx?thumb_id=0&image_path=/images/2014/9/8/Paulson_Sportfile.jpg")
georgia_southern.images.create(photo: "http://www.rosser.com/wp-content/uploads/2016/10/GaSouth_aerial-1000x656.jpg")
georgia_st.images.create(photo: "http://www.sportsonearth.com/assets/images/3/5/6/259152356/cuts/950x538/cut.jpg")
georgia_st.images.create(photo: "https://pbs.twimg.com/media/DIqZTHIVoAArswn.jpg")
georgia_st.images.create(photo: "https://img.grouponcdn.com/deal/4U83RMusE5cwnwGybNg9mLgYjxAk/4U-1000x446/v1/c700x420.jpg")
coastal_car.images.create(photo: "https://i.ytimg.com/vi/bNyQRFztb98/maxresdefault.jpg")
coastal_car.images.create(photo: "https://i.pinimg.com/736x/84/23/19/842319c3d4f715c91f0b2a1e06c6e071--good-night-to-win.jpg")
coastal_car.images.create(photo: "https://i.pinimg.com/originals/96/f6/d2/96f6d2a44bb0a0af28541387c8913571.jpg")
